name: hammer-ci
on:
  push:
    branches:
      - 'hammer-*'
  pull_request:
    branches:
      - 'hammer-*'
env:
  CLICOLOR_FORCE: 1
jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true
    - name: Run CI
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
