name: hammer-release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: workbench
            asset_name: workbench-linux-amd64
          - os: windows-latest
            artifact_name: workbench.exe
            asset_name: workbench-windows-amd64
          - os: macos-latest
            artifact_name: workbench
            asset_name: workbench-macos-amd64

    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: ./hammer
      run: cargo build --release --locked
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: hammer/target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
